# Generated by Django 5.2.16 on 2026-08-18 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='نامک')),
                ('job_title', models.CharField(max_length=120, verbose_name='سمت')),
                ('photo', models.ImageField(blank=True, upload_to='organization/photos/', verbose_name='تصویر')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='شماره تماس فقط می\u200cتواند شامل عدد، فاصله، علامت +، خط تیره و پرانتز باشد.', regex='^\\+?[0-9۰-۹()\\-\\s]+$')], verbose_name='شماره تماس')),
                ('rubika_url', models.URLField(blank=True, verbose_name='روبیکا')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('short_bio', models.CharField(blank=True, max_length=250, verbose_name='معرفی کوتاه')),
                ('bio', models.TextField(blank=True, verbose_name='معرفی کامل')),
                ('instagram_url', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='لینکدین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'عضو مجموعه',
                'verbose_name_plural': 'اعضای مجموعه',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
