# Generated by Django 5.2.16 on 2026-08-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='is_primary_manager',
            field=models.BooleanField(default=False, help_text='فقط یک عضو می\u200cتواند به\u200cعنوان مدیر اصلی سایت انتخاب شود.', verbose_name='مدیر اصلی'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_manager', True)), fields=('is_primary_manager',), name='unique_primary_organization_manager'),
        ),
    ]
