# Generated by Django 5.2.16 on 2026-07-31 09:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('locations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('reference_code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('under_construction', 'Under Construction'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('archived', 'Archived')], default='planning', max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=300)),
                ('developer_name', models.CharField(blank=True, max_length=150)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency_code', models.CharField(choices=[('IRR', 'Iranian Rial'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('AED', 'UAE Dirham')], default='IRR', max_length=3)),
                ('total_units', models.PositiveIntegerField(blank=True, null=True)),
                ('available_units', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_projects', to='agents.agent')),
                ('features', models.ManyToManyField(blank=True, related_name='development_projects', to='projects.projectfeature')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_projects', to='locations.region')),
            ],
            options={
                'verbose_name': 'Development Project',
                'verbose_name_plural': 'Development Projects',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'region'], name='projects_de_status_ec6d93_idx'), models.Index(fields=['is_featured', 'status'], name='projects_de_is_feat_e2ecd7_idx')],
            },
        ),
    ]
