# Generated by Django 5.2.16 on 2026-07-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_developmentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.developmentproject')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['display_order', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('project',), name='unique_cover_image_per_project')],
            },
        ),
    ]
