# Generated by Django 5.2.16 on 2026-08-04 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_options_remove_agent_whatsapp_and_more'),
        ('locations', '0001_initial'),
        ('projects', '0003_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentproject',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'پروژه ساختمانی', 'verbose_name_plural': 'پروژه\u200cهای ساختمانی'},
        ),
        migrations.AlterModelOptions(
            name='projectfeature',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'امکان پروژه', 'verbose_name_plural': 'امکانات پروژه'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['-is_cover', 'display_order', 'created_at'], 'verbose_name': 'تصویر پروژه', 'verbose_name_plural': 'تصاویر پروژه'},
        ),
        migrations.RemoveIndex(
            model_name='developmentproject',
            name='projects_de_status_ec6d93_idx',
        ),
        migrations.RemoveIndex(
            model_name='developmentproject',
            name='projects_de_is_feat_e2ecd7_idx',
        ),
        migrations.RemoveField(
            model_name='developmentproject',
            name='address',
        ),
        migrations.RemoveField(
            model_name='developmentproject',
            name='status',
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='construction_status',
            field=models.CharField(choices=[('planning', 'در مرحله برنامه\u200cریزی'), ('under_construction', 'در حال ساخت'), ('completed', 'تکمیل\u200cشده'), ('on_hold', 'متوقف\u200cشده')], default='planning', max_length=30, verbose_name='وضعیت ساخت'),
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='is_exact_location_public',
            field=models.BooleanField(default=False, help_text='فقط در صورت داشتن اجازه، موقعیت دقیق پروژه در سایت عمومی نمایش داده شود.', verbose_name='نمایش موقعیت دقیق در سایت'),
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='price_on_request',
            field=models.BooleanField(default=False, help_text='با فعال\u200cکردن این گزینه، ثبت قیمت شروع برای انتشار الزامی نیست.', verbose_name='قیمت توافقی یا تماس بگیرید'),
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='private_address',
            field=models.TextField(blank=True, help_text='این آدرس فقط برای استفاده داخلی مجموعه است و نباید در سایت عمومی نمایش داده شود.', verbose_name='آدرس دقیق داخلی'),
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='public_location',
            field=models.CharField(blank=True, help_text='موقعیت تقریبی قابل نمایش در سایت؛ مانند اسپندکلا، محدوده جاده اصلی', max_length=250, verbose_name='موقعیت عمومی'),
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار بررسی'), ('published', 'منتشرشده'), ('archived', 'بایگانی\u200cشده')], default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_projects', to='agents.agent', verbose_name='مشاور مسئول'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='available_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدهای موجود'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='currency_code',
            field=models.CharField(choices=[('IRT', 'تومان ایران'), ('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا'), ('EUR', 'یورو'), ('AED', 'درهم امارات')], default='IRT', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='description',
            field=models.TextField(verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='developer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام سازنده یا توسعه\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تقریبی تحویل'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='development_projects', to='projects.projectfeature', verbose_name='امکانات پروژه'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='پروژه ویژه'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='reference_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='کد پروژه'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_projects', to='locations.region', verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='معرفی کوتاه'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='slug',
            field=models.SlugField(help_text='برای آدرس صفحه پروژه، فقط از حروف انگلیسی، عدد و خط تیره استفاده شود.', max_length=220, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت شروع'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان پروژه'),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='total_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد کل واحدها'),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='icon',
            field=models.CharField(blank=True, max_length=80, verbose_name='آیکن'),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='نام امکان'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.developmentproject', verbose_name='پروژه'),
        ),
        migrations.AddIndex(
            model_name='developmentproject',
            index=models.Index(fields=['publication_status', 'construction_status'], name='project_pub_build_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentproject',
            index=models.Index(fields=['region', 'publication_status'], name='project_region_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentproject',
            index=models.Index(fields=['is_featured', 'publication_status'], name='project_featured_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='developmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('available_units__isnull', True), ('total_units__isnull', True), ('available_units__lte', models.F('total_units')), _connector='OR'), name='project_available_units_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='developmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('expected_completion_date__isnull', True), ('expected_completion_date__gte', models.F('start_date')), _connector='OR'), name='project_completion_date_gte_start'),
        ),
    ]
