# Generated by Django 5.2.16 on 2026-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_developmentproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentproject',
            name='currency_code',
            field=models.CharField(choices=[('IRT', 'تومان ایران'), ('USD', 'دلار آمریکا'), ('EUR', 'یورو'), ('AED', 'درهم امارات')], default='IRT', max_length=3, verbose_name='واحد پول'),
        ),
    ]
