# Generated by Django 5.2.16 on 2026-07-31 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('locations', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('reference_code', models.CharField(max_length=30, unique=True)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold'), ('rented', 'Rented'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency_code', models.CharField(choices=[('IRR', 'Iranian Rial'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('AED', 'UAE Dirham')], default='IRR', max_length=3)),
                ('building_area', models.PositiveIntegerField(blank=True, help_text='Building area in square metres', null=True)),
                ('land_area', models.PositiveIntegerField(blank=True, help_text='Land area in square metres', null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('parking_spaces', models.PositiveSmallIntegerField(default=0)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor_number', models.SmallIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='agents.agent')),
                ('features', models.ManyToManyField(blank=True, related_name='properties', to='properties.feature')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.region')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'listing_type'], name='properties__status_b35a4c_idx'), models.Index(fields=['region', 'property_type'], name='properties__region__61d0bb_idx'), models.Index(fields=['is_featured', 'status'], name='properties__is_feat_66aedb_idx')],
            },
        ),
    ]
