# Generated by Django 5.2.16 on 2026-08-04 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_options_remove_agent_whatsapp_and_more'),
        ('locations', '0001_initial'),
        ('projects', '0004_alter_developmentproject_options_and_more'),
        ('properties', '0003_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPrivateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exact_address', models.TextField(blank=True, verbose_name='آدرس دقیق')),
                ('owner_name', models.CharField(blank=True, max_length=150, verbose_name='نام مالک')),
                ('owner_phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='شماره تماس فقط می\u200cتواند شامل عدد، فاصله، علامت +، خط تیره و پرانتز باشد.', regex='^\\+?[0-9۰-۹()\\-\\s]+$')], verbose_name='شماره تماس مالک')),
                ('owner_notes', models.TextField(blank=True, verbose_name='یادداشت داخلی مالک')),
                ('exact_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='عرض جغرافیایی دقیق')),
                ('exact_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='طول جغرافیایی دقیق')),
            ],
            options={
                'verbose_name': 'اطلاعات خصوصی ملک',
                'verbose_name_plural': 'اطلاعات خصوصی املاک',
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'امکان ملک', 'verbose_name_plural': 'امکانات ملک'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-is_cover', 'display_order', 'created_at'], 'verbose_name': 'تصویر ملک', 'verbose_name_plural': 'تصاویر ملک'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'نوع ملک', 'verbose_name_plural': 'انواع ملک'},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__status_b35a4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__is_feat_66aedb_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='property_region_type_idx',
            old_name='properties__region__61d0bb_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.AddField(
            model_name='property',
            name='availability_status',
            field=models.CharField(choices=[('available', 'موجود'), ('reserved', 'رزروشده'), ('sold', 'فروخته\u200cشده'), ('rented', 'اجاره\u200cرفته'), ('unavailable', 'موقتاً غیرفعال')], default='available', max_length=20, verbose_name='وضعیت دسترسی'),
        ),
        migrations.AddField(
            model_name='property',
            name='deed_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='توضیح سند'),
        ),
        migrations.AddField(
            model_name='property',
            name='deed_type',
            field=models.CharField(choices=[('official_single_page', 'سند رسمی تک\u200cبرگ'), ('official_booklet', 'سند رسمی دفترچه\u200cای'), ('contractual', 'قولنامه\u200cای'), ('cooperative', 'تعاونی'), ('leasehold', 'حق بهره\u200cبرداری یا اجاره بلندمدت'), ('in_progress', 'سند در حال اقدام'), ('unknown', 'نامشخص')], default='unknown', max_length=30, verbose_name='نوع سند'),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ ودیعه یا رهن'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_document_verified',
            field=models.BooleanField(default=False, help_text='این گزینه صرفاً نشان\u200cدهنده بررسی داخلی است و تضمین حقوقی اصالت سند محسوب نمی\u200cشود.', verbose_name='مدارک توسط مجموعه بررسی شده است'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_exact_location_public',
            field=models.BooleanField(default=False, help_text='این گزینه فقط با اجازه مالک فعال شود. در حالت عادی از موقعیت تقریبی استفاده شود.', verbose_name='نمایش موقعیت دقیق در سایت'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_price_negotiable',
            field=models.BooleanField(default=False, verbose_name='قیمت قابل مذاکره است'),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='اجاره ماهانه'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_on_request',
            field=models.BooleanField(default=False, verbose_name='قیمت توافقی یا تماس بگیرید'),
        ),
        migrations.AddField(
            model_name='property',
            name='project',
            field=models.ForeignKey(blank=True, help_text='این فیلد فقط برای املاک و واحدهای وابسته به یک پروژه انتخاب شود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='projects.developmentproject', verbose_name='پروژه ساختمانی'),
        ),
        migrations.AddField(
            model_name='property',
            name='public_location',
            field=models.CharField(blank=True, help_text='موقعیت تقریبی قابل نمایش در سایت؛ مانند اسپندکلا، محدوده جاده اصلی', max_length=250, verbose_name='موقعیت عمومی'),
        ),
        migrations.AddField(
            model_name='property',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار بررسی'), ('published', 'منتشرشده'), ('archived', 'بایگانی\u200cشده')], default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت فروش'),
        ),
        migrations.AddField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('mortgage_rent', 'رهن و اجاره'), ('full_mortgage', 'رهن کامل'), ('pre_sale', 'پیش\u200cفروش')], default='sale', max_length=20, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, max_length=80, verbose_name='آیکن'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='نام امکان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='agents.agent', verbose_name='مشاور مسئول'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد حمام و سرویس'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_area',
            field=models.PositiveIntegerField(blank=True, help_text='برحسب مترمربع', null=True, verbose_name='متراژ بنا'),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency_code',
            field=models.CharField(choices=[('IRT', 'تومان ایران'), ('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا'), ('EUR', 'یورو'), ('AED', 'درهم امارات')], default='IRT', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.feature', verbose_name='امکانات ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='شماره طبقه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ملک ویژه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.PositiveIntegerField(blank=True, help_text='برحسب مترمربع', null=True, verbose_name='متراژ زمین'),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='عرض جغرافیایی عمومی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='طول جغرافیایی عمومی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد پارکینگ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype', verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='reference_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='کد ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.region', verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(help_text='برای آدرس صفحه ملک، از حروف انگلیسی، عدد و خط تیره استفاده شود.', max_length=220, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد کل طبقات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, help_text='سال شمسی یا میلادی به\u200cصورت چهاررقمی وارد شود.', null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='ملک'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام نوع ملک'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='slug',
            field=models.SlugField(help_text='برای آدرس صفحه نوع ملک، از حروف انگلیسی، عدد و خط تیره استفاده شود.', max_length=120, unique=True, verbose_name='نامک'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['publication_status', 'availability_status', 'transaction_type'], name='property_pub_avail_tx_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['project', 'publication_status'], name='property_project_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', 'publication_status'], name='property_featured_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='prop_sale_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__isnull', True), ('deposit_amount__gte', 0), _connector='OR'), name='prop_deposit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__isnull', True), ('monthly_rent__gte', 0), _connector='OR'), name='prop_monthly_rent_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('floor_number__isnull', True), ('total_floors__isnull', True), ('floor_number__lte', models.F('total_floors')), _connector='OR'), name='prop_floor_lte_total'),
        ),
        migrations.AddField(
            model_name='propertyprivatedetails',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_details', to='properties.property', verbose_name='ملک'),
        ),
    ]
