# Generated by Django 5.2.16 on 2026-07-31 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0003_projectimage'),
        ('properties', '0003_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='phone', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to='agents.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='projects.developmentproject')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='properties.property')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='inquiries_i_status_38a868_idx'), models.Index(fields=['phone'], name='inquiries_i_phone_a0e615_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('property__isnull', False), ('project__isnull', False), _negated=True), name='inquiry_cannot_target_property_and_project')],
            },
        ),
    ]
