# Generated by Django 5.2.16 on 2026-08-04 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_options_remove_agent_whatsapp_and_more'),
        ('inquiries', '0001_initial'),
        ('projects', '0003_projectimage'),
        ('properties', '0003_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست مشتری', 'verbose_name_plural': 'درخواست\u200cهای مشتری'},
        ),
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='inquiry_status_created_idx',
            old_name='inquiries_i_status_38a868_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='inquiry_phone_idx',
            old_name='inquiries_i_phone_a0e615_idx',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت داخلی'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to='agents.agent', verbose_name='مشاور مسئول'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(verbose_name='پیام مشتری'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='شماره تماس فقط می\u200cتواند شامل عدد، فاصله، علامت +، خط تیره و پرانتز باشد.', regex='^\\+?[0-9۰-۹()\\-\\s]+$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'تلفن'), ('rubika', 'روبیکا'), ('email', 'ایمیل')], default='phone', max_length=20, verbose_name='روش ارتباط ترجیحی'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='projects.developmentproject', verbose_name='پروژه مرتبط'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='properties.property', verbose_name='ملک مرتبط'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته\u200cشده'), ('in_progress', 'در حال پیگیری'), ('closed', 'بسته\u200cشده'), ('spam', 'هرزنامه')], default='new', max_length=20, verbose_name='وضعیت پیگیری'),
        ),
    ]
