# Generated by Django 5.2.16 on 2026-08-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['city__name', 'name'], 'verbose_name': 'منطقه', 'verbose_name_plural': 'مناطق'},
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(help_text='برای آدرس صفحه، از حروف انگلیسی، عدد و خط تیره استفاده شود.', max_length=140, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='locations.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام منطقه'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(help_text='برای آدرس صفحه، از حروف انگلیسی، عدد و خط تیره استفاده شود.', max_length=140, verbose_name='نامک'),
        ),
    ]
