# Generated by Django 5.2.16 on 2026-08-04 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['display_order', 'full_name'], 'verbose_name': 'مشاور', 'verbose_name_plural': 'مشاوران'},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='agent',
            name='rubika_url',
            field=models.URLField(blank=True, help_text='مثال: https://rubika.ir/username', verbose_name='لینک روبیکا'),
        ),
        migrations.AddField(
            model_name='agent',
            name='service_regions',
            field=models.ManyToManyField(blank=True, related_name='agents', to='locations.region', verbose_name='مناطق فعالیت'),
        ),
        migrations.AddField(
            model_name='agent',
            name='short_bio',
            field=models.CharField(blank=True, help_text='متن کوتاه برای نمایش در کارت مشاور', max_length=250, verbose_name='معرفی کوتاه'),
        ),
        migrations.AddField(
            model_name='agent',
            name='specialties',
            field=models.CharField(blank=True, help_text='مثال: خرید و فروش ویلا، زمین و پروژه\u200cهای ساختمانی', max_length=250, verbose_name='تخصص\u200cها'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True, verbose_name='معرفی کامل'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, help_text='تعداد سال\u200cهای سابقه فعالیت', validators=[django.core.validators.MinValueValidator(0)], verbose_name='سابقه کاری'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='مشاور فعال در بخش عمومی سایت قابل نمایش است.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مشاور ویژه'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='job_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='شماره تماس فقط می\u200cتواند شامل عدد، فاصله، علامت +، خط تیره و پرانتز باشد.', regex='^\\+?[0-9۰-۹()\\-\\s]+$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='agents/photos/', verbose_name='تصویر مشاور'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=models.SlugField(help_text='برای آدرس صفحه مشاور، فقط از حروف انگلیسی استفاده شود.', max_length=170, unique=True, verbose_name='نامک'),
        ),
    ]
