# Generated by Django 5.2.16 on 2026-08-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_options_remove_agent_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='rubika_url',
            field=models.CharField(blank=True, help_text='آیدی یا لینک روبیکا را وارد کنید.', max_length=255, verbose_name='روبیکا'),
        ),
    ]
